# settings.py
"""
CẤU HÌNH ĐỘ NHẠY CHO GAME
"""

MIN_DETECTION_CONFIDENCE = 0.4
MIN_TRACKING_CONFIDENCE = 0.4
FINGER_UP_THRESHOLD = 0.0
ATTACK_RANGE = 150
BULLET_SIZE = (10, 6)
ENEMY_HITBOX_INFLATE = 20
PROCESS_INTERVAL = 1.0 / 30
GESTURE_COOLDOWN = 4
GESTURE_STABLE_THRESHOLD = 2
SWIPE_THRESHOLD = 0.025
LIFT_THRESHOLD = 0.035
MOTION_COOLDOWN = 5

FOLLOW_HAND_MODE = True
FOLLOW_HAND_SMOOTHING = 0.25
FOLLOW_MARGIN = 40
FOLLOW_MAX_SPEED = 15

SENSITIVITY_PRESETS = {
    "very_low": {
        "MIN_DETECTION_CONFIDENCE": 0.7,
        "MIN_TRACKING_CONFIDENCE": 0.7,
        "SWIPE_THRESHOLD": 0.05,
        "LIFT_THRESHOLD": 0.08,
        "ATTACK_RANGE": 120,
    },
    "low": {
        "MIN_DETECTION_CONFIDENCE": 0.6,
        "MIN_TRACKING_CONFIDENCE": 0.6,
        "SWIPE_THRESHOLD": 0.04,
        "LIFT_THRESHOLD": 0.06,
        "ATTACK_RANGE": 130,
    },
    "normal": {
        "MIN_DETECTION_CONFIDENCE": 0.5,
        "MIN_TRACKING_CONFIDENCE": 0.5,
        "SWIPE_THRESHOLD": 0.03,
        "LIFT_THRESHOLD": 0.05,
        "ATTACK_RANGE": 150,
    },
    "high": {
        "MIN_DETECTION_CONFIDENCE": 0.4,
        "MIN_TRACKING_CONFIDENCE": 0.4,
        "SWIPE_THRESHOLD": 0.025,
        "LIFT_THRESHOLD": 0.035,
        "ATTACK_RANGE": 170,
    },
    "very_high": {
        "MIN_DETECTION_CONFIDENCE": 0.3,
        "MIN_TRACKING_CONFIDENCE": 0.3,
        "SWIPE_THRESHOLD": 0.02,
        "LIFT_THRESHOLD": 0.025,
        "ATTACK_RANGE": 200,
    }
}

ACTIVE_PRESET = "very_high"

def apply_preset(preset_name):
    global MIN_DETECTION_CONFIDENCE, MIN_TRACKING_CONFIDENCE
    global SWIPE_THRESHOLD, LIFT_THRESHOLD, ATTACK_RANGE
    
    preset = SENSITIVITY_PRESETS.get(preset_name, SENSITIVITY_PRESETS["normal"])
    MIN_DETECTION_CONFIDENCE = preset["MIN_DETECTION_CONFIDENCE"]
    MIN_TRACKING_CONFIDENCE = preset["MIN_TRACKING_CONFIDENCE"]
    SWIPE_THRESHOLD = preset["SWIPE_THRESHOLD"]
    LIFT_THRESHOLD = preset["LIFT_THRESHOLD"]
    ATTACK_RANGE = preset["ATTACK_RANGE"]
    
    print(f"✅ Đã áp dụng preset: {preset_name}")

apply_preset(ACTIVE_PRESET)